# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim-buster

WORKDIR /app
COPY requirements.txt .
COPY . /app

RUN python -m pip install -r requirements.txt

CMD python seeker.py